VERSION="2.2.1"

ACCOUNTS=["GBJOSGB57IKOMYUBTJDPWWN6YUICAQ7WNU7CKWC77DH4BI2UXKHMBECK"]

[DOCUMENTATION]
ORG_NAME="VanEck"
ORG_URL="https://www.vaneckstellar.org/"
ORG_DESCRIPTION="VanEck is an American investment management firm headquartered in New York City. The firm is primarily engaged in issuing exchange-traded fund products although it also deals with mutual funds and separately managed accounts for institutional investors."
ORG_LOGO="https://www.vaneckstellar.org/ETHV.png"


[[CURRENCIES]]
code="ETHV"
status="live"
display_decimals=4
issuer="GBJOSGB57IKOMYUBTJDPWWN6YUICAQ7WNU7CKWC77DH4BI2UXKHMBECK"
anchor_asset_type="crypto"
name="ETH VanEck"
desc="VanEck's Ethereum ETF Ticker “ETHV” Listed."
image="https://www.vaneckstellar.org/ETHV.png"
